# Generated by Django 5.0.4 on 2024-12-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
